name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Build
      run: |
        pip install virtualenv ipython nbconvert jedi numpy scipy jep==3.9.0
        jep_site_packages_path=`pip show jep | grep "^Location:" | cut -d ':' -f 2 | cut -d ' ' -f 2`
        jep_path=${jep_site_packages_path}/jep
        jep_lib_path=`realpath ${jep_site_packages_path}/../../`
        export LD_LIBRARY_PATH=${jep_path}:${jep_site_packages_path}:${jep_lib_path}:${LD_LIBRARY_PATH}
        export LD_PRELOAD=${jep_lib_path}/libpython3.so
        cd $GITHUB_WORKSPACE
        sbt +test
